---
title: "Homework 1"
author: Group 7 -Mohamad Rushdi sweid- Abdulrahman Kalam -Osama Alshurbaji-Abdullah
  Badr
date: "October 7, 2017"
output: word_document

First Q : 
2 coins Tossed , colored cube has 4 different colours , 4 cards have different faces   How many different number of outcomes are there for this experiment? 

Solution: Multiplication rule. n1n2n3 = 4.4.(4.2) = 128                              n1 <- 4 # 2 coins have 4  potential outcomes.                                       n2 <- 4 #4 coloured cube have 4 potential outcomes.                                 n3 <- 8 #4 cards draw have 8 potential 
  
 2nd Q:  in HOw many ways can I order these countries : (Syria,Turkey,Russia,Germany,Egypt and Brazil) To present thier countries in 2 groups.
                                                                                      Solution : permetation Rule. n! = 6! r = 2!                                                                                    6!/(6-2)! = 30 
                                                                                      
  3rd Q : we have 50 employees , 20 sicintist , 18 doctors and 12 assistants and we want to form a group of 3 persons and each group should have 1S.1D.1A            in how many ways can we form such a group ?                                           
   Solutions by combination rule : (n,r) = (50,3)-(20,3)-(18,3)-(12,3) = 17424